Exercice 7

In [4]:
import numpy as np
lol = [[1,2,1,1],[0,1,2,1],[1,0,1,2],[2,1,0,1]]
lol = np.array(lol)
mdr = np.array([0,0,1,0])
print(lol)
print(mdr)
print(np.linalg.det(lol))
solve = np.linalg.solve(lol,mdr)
print(solve)
np.dot(lol,solve)

[[1 2 1 1]
 [0 1 2 1]
 [1 0 1 2]
 [2 1 0 1]]
[0 0 1 0]
-4.0
[-0.5  0.  -0.5  1. ]


array([0., 0., 1., 0.])

Exercice 5

In [17]:
matrice = np.arange(50*50).reshape(50,50)
def oups(x):
    i = 0
    happy = list()
    ra = np.array(x)
    happy = np.array(happy)
    for i in range(np.size(ra,1)):
            j = 1; 
            for j in range(np.size(ra,0)):
                thingy = np.absolute(ra[i][j] - ra[i][j-1])
                happy = np.append(happy, thingy)
    return np.max(happy)
print(oups(matrice))

49.0


Exercie 3

In [23]:
meh = np.full((1,8),1)
meh = np.append(meh, [])

meh_cpy = np.copy(meh)
meeuh = (np.full((1,7),0))
meeuh = np.append(meeuh, [1])
i = 0
for i in range(6):
    meh = np.column_stack((meh,meeuh))
meh = np.column_stack((meh,meh_cpy))
print(meh)


[[1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [29]:
machin = np.zeros((7,6))
truc = np.full((7,1),1)

fruit = np.full((1,8),1)

ploup = np.concatenate((truc,machin,truc), 1) #1 valeur des axes (ordonné)

ploup = np.concatenate((ploup,fruit), 0) # 0 abscisse 
print(ploup)


[[1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Exercice 1

In [34]:
A = np.arange(0,100,3)

B = np.sin(A*A)*(np.pi/2) #np.sin donne une val entre -1 et 1 
print(B)
C = np.max(B)
print(C)

np.sum([B==C])

[ 0.          0.6473542  -1.55788258 -0.98942575 -0.77129492 -1.46098962
 -0.63470416  1.4505833  -1.39165137  0.2355202   1.56734572  1.4224189
  1.56400388  0.71020939 -1.57078197  1.52444478 -1.47109066 -0.3714248
  0.88955203  0.87809717 -0.41168052 -1.44537754  1.54491339 -1.56530168
  0.57112995  1.57042833  1.497909    1.53420846 -0.02685925 -1.23366009
  1.29939169 -0.30502216 -1.55587358 -1.09244783]
1.5704283348055927


1.5704283348055927

Exo 2

In [ ]:
X = [[1,2,3],
    [4,5,6],
    [0,0,9]]
X = np.array(X)
def coucou(M):
    return (M == np.triu(np.tril(M))).all()
def salut(M):
    return (M == np.triu(M)).all()

Exo 4

In [42]:

def hoho(n):
    i = 0
    res = 0
    for i in range(n+1):
        res = res + i
        
        print(str(i) + " " + str(res))
    return res

def haha(n):
    return np.sum(np.arange(n+1))


10

Exercice 6

In [49]:
import numpy as np

ko = np.random.rand(50,50) # fct rand = nbre aléatoire entre 0 et 1 np.random = fonctions numpy qui crée des nbres aléatoires
i = 0
print(ko)
print(np.sum(ko<0.5))
for i in range(len(ko)): #ou range(np.size(ko,1))
    j = 0
    for j in range(len(ko[i])): #ou range(np.size(ko,0))
        if (ko[i][j] < 0.5):
            ko[i][j] = 0
        else:
            ko[i][j] = 1

print(ko)
        

[[0.33074926 0.38480567 0.57998844 ... 0.92684997 0.85767452 0.74049978]
 [0.03868936 0.50954033 0.3013898  ... 0.08600607 0.63148548 0.64304793]
 [0.36859282 0.31937753 0.04148933 ... 0.33294128 0.92568301 0.43274967]
 ...
 [0.13502272 0.22948432 0.88993061 ... 0.07196434 0.13466195 0.3196376 ]
 [0.51644816 0.087232   0.91244194 ... 0.46515869 0.74296205 0.1308394 ]
 [0.91699234 0.7790765  0.41161053 ... 0.19446655 0.87074118 0.89744457]]
1276
[[0. 0. 1. ... 1. 1. 1.]
 [0. 1. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 [1. 1. 0. ... 0. 1. 1.]]
